name: Test Workflow
on: 
  push:
    branches: 
      - main

jobs:
  example-job: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Print a Welcome Message
        run: echo "Welcome to my App"

      - name: Checkout Repository
        uses: actions/checkout@v5.0.0

      - name: Listing Repository Files
        run: ls -la
